### ISSUE TITLE
Add option to hide XivEsp button from info bar when no filter is set

### ISSUE THREAD

**Issue by RhapsodySL** [VariableVixen/XivEsp#1]
At this time the XivEsp button appears all the time on the info bar, which isn't terribly useful if a filter isn't set. It'd be nice to have an option to have it disappear if there isn't currently a filter set.

**Comment by VariableVixen** [comment]
I'll look into this one Dawntrail is out, but I'm not updating any of my plugins until then since there may be Dalamud changes to adjust for as well.

**Comment by VariableVixen** [comment]
Good news! This is super easy to implement in the new API, so it'll be available shortly.
