### ISSUE TITLE
Feature Request - Chat Channel for Output

### ISSUE THREAD

**Issue by mphartzheim** [VariableVixen/XivEsp#2]
Would love to be able to select which chat channel the text output goes to so I can control which window it appears in. Specifically I'd like to use the Echo channel that some other plugins also use.

Thanks!

**Comment by VariableVixen** [comment]
I'm calling this low priority because at this point, I'm gonna have to make an actual GUI for settings, but yeah I'll see what I can do. No promises on speed though, I finally started playing DT myself a few days ago.

**Comment by VariableVixen** [comment]
Implemented and released
